---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "balance-transfer"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Balance Transfer Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see gfe.yaml and deke.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  softwarechannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - dbiir.orderer.com
      - deke.orderer.com
      - gfe.orderer.com

    # Required. list of peers from participating orgs
    peers:
      peer0.fabric.gfe.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.fabric.gfe.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.fabric.deke.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.fabric.deke.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  Gfe:
    mspid: GfeMSP

    peers:
      - peer0.fabric.gfe.com
      - peer1.fabric.gfe.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-gfe

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.gfe.com/users/Admin@fabric.gfe.com/msp/keystore/b841a46e02fa82d82ab384435f4cca840c64d8dccae75fe8b52ec6d07233916a_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.gfe.com/users/Admin@fabric.gfe.com/msp/signcerts/Admin@fabric.gfe.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  Deke:
    mspid: DekeMSP
    peers:
      - peer0.fabric.deke.com
      - peer1.fabric.deke.com
    certificateAuthorities:
      - ca-deke
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.deke.com/users/Admin@fabric.deke.com/msp/keystore/b648e7e71db265e862e2ac72dde1c661133d412dac4869792141dbc8bceb24b2_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.deke.com/users/Admin@fabric.deke.com/msp/signcerts/Admin@fabric.deke.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  dbiir.orderer.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: dbiir.orderer.com
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/orderer.com/orderers/dbiir.orderer.com/tls/ca.crt

  deke.orderer.com:
    url: grpcs://localhost:8050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: deke.orderer.com
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/orderer.com/orderers/deke.orderer.com/tls/ca.crt

  gfe.orderer.com:
    url: grpcs://localhost:9050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: gfe.orderer.com
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/orderer.com/orderers/gfe.orderer.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.fabric.gfe.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.fabric.gfe.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.gfe.com/peers/peer0.fabric.gfe.com/tls/ca.crt

  peer1.fabric.gfe.com:
    url: grpcs://localhost:7056
    eventUrl: grpcs://localhost:7058
    grpcOptions:
      ssl-target-name-override: peer1.fabric.gfe.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.gfe.com/peers/peer1.fabric.gfe.com/tls/ca.crt

  peer0.fabric.deke.com:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer0.fabric.deke.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.deke.com/peers/peer0.fabric.deke.com/tls/ca.crt

  peer1.fabric.deke.com:
    url: grpcs://localhost:8056
    eventUrl: grpcs://localhost:8058
    grpcOptions:
      ssl-target-name-override: peer1.fabric.deke.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.deke.com/peers/peer1.fabric.deke.com/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-gfe:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.gfe.com/ca/ca.fabric.gfe.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-gfe

  ca-deke:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/fabric.deke.com/ca/ca.fabric.deke.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-deke
