version: '2'
services:

    couchdb1:
      image: hyperledger/fabric-couchdb
      restart: always
      tty: true
      container_name: couchdb1
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
      ports:
      - "5984:5984"  # this is the restful API addr, can also access fauxton web ui thru http://localhost:5984/_utils/  


    peer1.fabric.gfe.com:
      container_name: peer1.fabric.gfe.com
      image: hyperledger/fabric-peer
      environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # The following setting skips the gossip handshake since we are
      # are not doing mutual TLS
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      #- CORE_CHAINCODE_EXECUTETIMEOUT=25920000s
      - CORE_CHAINCODE_EXECUTETIMEOUT=200s
      - CORE_PEER_ID=peer1.fabric.gfe.com
      - CORE_PEER_LOCALMSPID=GfeMSP
      - CORE_PEER_ADDRESS=peer1.fabric.gfe.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      volumes:
        - /var/run/:/host/var/run/
        - ./channel/crypto-config/peerOrganizations/fabric.gfe.com/peers/peer0.fabric.gfe.com/:/etc/hyperledger/crypto/peer
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: peer node start
      ports:
        - 7051:7051
        - 7053:7053
      depends_on:
        - couchdb1
      extra_hosts:  # 声明域名和IP的对应关系
        - "dbiir.orderer.com:10.77.70.174"
        - "deke.orderer.com:10.77.70.175"
        - "gfe.orderer.com:10.77.70.176"
        - "peer0.fabric.gfe.com:10.77.70.174" 
        - "peer0.fabric.deke.com:10.77.70.176" 
        - "peer1.fabric.deke.com:10.77.70.177"
        
  

