version: '2'
services:
  nacos-server-1:
    image: registry.cn-hangzhou.aliyuncs.com/nacos-fabric/nacos-server:1.3.1
    container_name: nacos-server1
    restart: always
    network_mode: "host"
    environment:
      PREFER_HOST_MODE: ip 
      NACOS_SERVER_IP: 10.77.70.175
      NACOS_SERVERS: 10.77.70.175:8848 10.77.70.177:8848 10.77.70.178:8848
    logging:
      driver: "none"
    ports:
      - "8848:8848"
      - "9555:9555"



#  nacos-server2:
#    image: modriclee/nacos-server-1.2:latest
#    container_name: nacos-server2
#    restart: always
#    networks:
#      default:
#        ipv4_address: 172.16.12.13
#    ports:
#      - "8849:8848"
#
#  nacos-server3:
#    image: modriclee/nacos-server-1.2:latest
#    container_name: nacos-server3
#    networks:
#      default:
#        ipv4_address: 172.16.12.14
#    ports:
#      - "8850:8848"

#  provider:
#    image: bolingcavalry/nacossimpleprovider:1.0-SNAPSHOT
#    links:
#      - nacos:nacoshost
#    depends_on:
#      - nacos
#  consumer:
#    image: bolingcavalry/nacossimpleconsumer:1.0-SNAPSHOT
#    links:
#      - nacos:nacoshost
#    container_name: consumer
#    depends_on:
#      - nacos
#    ports:
#      - '8080:8080'

