version: '2'
services:
  nacos-server-1:
    image: registry.cn-hangzhou.aliyuncs.com/nacos-fabric/nacos-server:1.3.1
    container_name: nacos-server1
    restart: always
    network_mode: "host"
    extra_hosts:
    - puwei-1.novalocal:10.77.70.173
    - puwei-2.novalocal:10.77.70.174
    - puwei-3.novalocal:10.77.70.175
    - puwei-4.novalocal:10.77.70.176
    - puwei-5.novalocal:10.77.70.177
    - puwei-6.novalocal:10.77.70.178
    - puwei-7.novalocal:10.77.70.179
    - puwei-8.novalocal:10.77.70.180
    - puwei-9.novalocal:10.77.70.181
    - puwei-10.novalocal:10.77.70.182
    - puwei-11.novalocal:10.77.70.183
    - puwei-12.novalocal:10.77.70.184
    - puwei-13.novalocal:10.77.70.185
    - puwei-14.novalocal:10.77.70.186
    - puwei-15.novalocal:10.77.70.187
    environment:
      PREFER_HOST_MODE: ip 
      NACOS_SERVER_IP: 10.77.70.175
      NACOS_SERVERS: 10.77.70.175:8848 10.77.70.177:8848 10.77.70.178:8848
    logging:
      driver: "none"
    ports:
      - "8848:8848"
      - "9555:9555"

  nacos-server-2:
    image: registry.cn-hangzhou.aliyuncs.com/nacos-fabric/nacos-server:1.3.1
    container_name: nacos-server2
    restart: always
    network_mode: "host"
    extra_hosts:
    - puwei-1.novalocal:10.77.70.173
    - puwei-2.novalocal:10.77.70.174
    - puwei-3.novalocal:10.77.70.175
    - puwei-4.novalocal:10.77.70.176
    - puwei-5.novalocal:10.77.70.177
    - puwei-6.novalocal:10.77.70.178
    - puwei-7.novalocal:10.77.70.179
    - puwei-8.novalocal:10.77.70.180
    - puwei-9.novalocal:10.77.70.181
    - puwei-10.novalocal:10.77.70.182
    - puwei-11.novalocal:10.77.70.183
    - puwei-12.novalocal:10.77.70.184
    - puwei-13.novalocal:10.77.70.185
    - puwei-14.novalocal:10.77.70.186
    - puwei-15.novalocal:10.77.70.187
    environment:
      PREFER_HOST_MODE: ip 
      NACOS_SERVER_IP: 10.77.70.177
      NACOS_SERVERS: 10.77.70.175:8848 10.77.70.177:8848 10.77.70.178:8848
    logging:
      driver: "none"
    ports:
      - "8848:8848"
      - "9555:9555"

  nacos-server-3:
    image: registry.cn-hangzhou.aliyuncs.com/nacos-fabric/nacos-server:1.3.1
    container_name: nacos-server3
    restart: always
    network_mode: "host"
    extra_hosts:
    - puwei-1.novalocal:10.77.70.173
    - puwei-2.novalocal:10.77.70.174
    - puwei-3.novalocal:10.77.70.175
    - puwei-4.novalocal:10.77.70.176
    - puwei-5.novalocal:10.77.70.177
    - puwei-6.novalocal:10.77.70.178
    - puwei-7.novalocal:10.77.70.179
    - puwei-8.novalocal:10.77.70.180
    - puwei-9.novalocal:10.77.70.181
    - puwei-10.novalocal:10.77.70.182
    - puwei-11.novalocal:10.77.70.183
    - puwei-12.novalocal:10.77.70.184
    - puwei-13.novalocal:10.77.70.185
    - puwei-14.novalocal:10.77.70.186
    - puwei-15.novalocal:10.77.70.187
    environment:
      PREFER_HOST_MODE: ip 
      NACOS_SERVER_IP: 10.77.70.178
      NACOS_SERVERS: 10.77.70.175:8848 10.77.70.177:8848 10.77.70.178:8848
    logging:
      driver: "none"
    ports:
      - "8848:8848"
      - "9555:9555"
